whistlewatchcards/jobboard/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path("", views.IndexView.as_view(), name="index"),
    path("ping", views.current_datetime, name="ping"),
    path("signin", views.signin, name="signin"),
    path("create-account", views.create_account, name="create-account"),
    path("job/<uuid:job_id>", views.JobDetailView.as_view(), name="job-detail"),
    path("job/add", views.JobCreateView.as_view(), name="job-add"),
    path("job/<uuid:job_id>/apply", views.job_apply, name="job-apply"),
]

whistlewatchcards/whistlewatchcards/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("", include("jobboard.urls")),
    path("admin/", admin.site.urls),
]

whistlewatchcards/jobboard/models.py
import uuid
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.urls import reverse
from phonenumber_field.modelfields import PhoneNumberField


class User(AbstractUser):
    phone_number = PhoneNumberField(blank=True)


class Club(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    name = models.CharField(max_length=64)


class Assignor(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    clubs = models.ManyToManyField(Club, through="AssignorClub")


class AssignorClub(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    club = models.ForeignKey(Club, on_delete=models.CASCADE)
    assignor = models.ForeignKey(Assignor, on_delete=models.CASCADE)
    admin = models.BooleanField()


class Job(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    title = models.TextField(blank=True)
    assignor = models.ForeignKey(Assignor, on_delete=models.CASCADE)
    club = models.ForeignKey(Club, on_delete=models.CASCADE)
    home_team = models.CharField(max_length=128)
    away_team = models.CharField(max_length=128)
    date_time = models.DateTimeField()
    address_1 = models.CharField(max_length=128)
    address_2 = models.CharField(max_length=128, blank=True)
    city = models.CharField(max_length=64)
    state = models.CharField(max_length=2)
    zip_code = models.CharField(max_length=5)
    location = models.CharField(max_length=128)
    league = models.CharField(max_length=128, blank=True)
    pay = models.DecimalField(max_digits=6, decimal_places=2, blank=True, null=True)
    notes = models.TextField(blank=True)
    created_at = models.DateTimeField(auto_now_add=True)

    def get_absolute_url(self):
        return reverse("job-detail", kwargs={"job_id": self.id})
    


class Referee(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    applications = models.ManyToManyField(
        Job, through="Application", related_name="applied"
    )
    assignments = models.ManyToManyField(
        Job, through="Assignment", related_name="assigned"
    )
    clubs = models.ManyToManyField(Club)


class Assignment(models.Model):
    POSITIONS = {
        "C": "Center Referee",
        "AR": "Assistant Referee",
        "FAR": "Fourth Official",
        "VAR": "Video Assistant Referee",
    }

    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    position = models.CharField(max_length=3, choices=POSITIONS)
    referee = models.ForeignKey(
        Referee, on_delete=models.CASCADE, blank=True, null=True
    )
    job = models.ForeignKey(Job, on_delete=models.CASCADE)


class Application(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    referee = models.ForeignKey(Referee, on_delete=models.CASCADE)
    job = models.ForeignKey(Job, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)

whistlewatchcards/jobboard/views.py
import datetime
from django.http import HttpResponse
from django.views.generic import ListView, DetailView, CreateView

from jobboard.models import Job


class IndexView(ListView):
    model = Job
    template_name = "index.html"


def current_datetime(request):
    now = datetime.datetime.now()
    html = "<html><body>It is now %s.</body></html>" % now
    return HttpResponse(html)


def signin(request):
    return HttpResponse("Signin page.")


def create_account(request):
    return HttpResponse("Create account page.")


def job_details(request):
    return HttpResponse("Job details page.")

class JobDetailView(DetailView):
    model = Job
    template_name = "job_detail.html"

    def get_object(self, queryset=None):
        return Job.objects.get(id=self.kwargs.get("job_id"))
    
class JobCreateView(CreateView):
    model = Job
    template_name = "job_add.html"
    fields = ["assignor", "club", "home_team", "away_team", "date_time", "address_1", "address_2", "city", "state", "zip_code", "location", "league", "notes"]


def job_apply(request):
    return HttpResponse("Job apply page.")

whistlewatchcards/jobboard/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
      <head>
            <meta charset="UTF-8">
            <meta name="viewport" content="width=device-width, initial-scale=1.0">
            <meta name="description"
                  content="Find and apply to soccer referee jobs in your area.">
            <meta name="keywords" content="HTML, CSS, JavaScript">
            <link rel="preconnect" href="https://fonts.googleapis.com">
            <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
            <link href="https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap"
                  rel="stylesheet">
            <link rel="stylesheet" href="{% static 'jobboard/reset.css' %}">
            <link rel="stylesheet" href="{% static 'jobboard/style.css' %}">
            <title>
                  {% comment %}
                        Whitespace is added around the title, can look into removing it
                  {% endcomment %}
                  {% block title %}
                        Whistle Watch Cards
                  {% endblock title %}
            </title>
      </head>
      <body>
            <header>
                  <div class="container">
                        <h1 class="sr-only">WhistleWatchCards</h1>
                        <a href="{% url "index" %}">
                              <svg class="icon"
                                   xmlns="http://www.w3.org/2000/svg"
                                   viewBox="0 0 512 512"
                                   aria-hidden="true">
                                    <!--!Font Awesome Free 6.5.2 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license/free Copyright 2024 Fonticons, Inc.-->
                                    <path d="M417.3 360.1l-71.6-4.8c-5.2-.3-10.3 1.1-14.5 4.2s-7.2 7.4-8.4 12.5l-17.6 69.6C289.5 445.8 273 448 256 448s-33.5-2.2-49.2-6.4L189.2 372c-1.3-5-4.3-9.4-8.4-12.5s-9.3-4.5-14.5-4.2l-71.6 4.8c-17.6-27.2-28.5-59.2-30.4-93.6L125 228.3c4.4-2.8 7.6-7 9.2-11.9s1.4-10.2-.5-15l-26.7-66.6C128 109.2 155.3 89 186.7 76.9l55.2 46c4 3.3 9 5.1 14.1 5.1s10.2-1.8 14.1-5.1l55.2-46c31.3 12.1 58.7 32.3 79.6 57.9l-26.7 66.6c-1.9 4.8-2.1 10.1-.5 15s4.9 9.1 9.2 11.9l60.7 38.2c-1.9 34.4-12.8 66.4-30.4 93.6zM256 512A256 256 0 1 0 256 0a256 256 0 1 0 0 512zm14.1-325.7c-8.4-6.1-19.8-6.1-28.2 0L194 221c-8.4 6.1-11.9 16.9-8.7 26.8l18.3 56.3c3.2 9.9 12.4 16.6 22.8 16.6h59.2c10.4 0 19.6-6.7 22.8-16.6l18.3-56.3c3.2-9.9-.3-20.7-8.7-26.8l-47.9-34.8z" />
                              </svg>
                              <span class="sr-only">Homepage</span>
                        </a>
                        <nav>
                              <ul>
                                    <li>
                                          <a href="{% url "signin" %}">Sign in</a>
                                    </li>
                              </ul>
                        </nav>
                  </div>
            </header>
            <main>
                  {% block content %}
                  {% endblock content %}
            </main>
      </body>
</html>

whistlewatchcards/jobboard/templates/index.html
{% extends "base.html" %}
{% load static %}
{% block title %}
 Homepage - Whistle Watch Cards
{% endblock title %}
{% block content %}
 <section class="hero">
  <h2>Find Soccer Referee Jobs Near You</h2>
  <img src="{% static "jobboard/images/referee-red-card-hand-drawn.webp" %}" alt="A hand-drawn hand holding up a red card from soccer" width="250" height="250" />
 </section>
 <section class="job-list">
  <ul>
   {% for job in job_list %}
    <li>
     <a href="{{ job.get_absolute_url }}">
      {% if job.title %}
       <h2>{{ job.title }}</h2>
      {% else %}
       <h2>{{ job.home_team }} vs. {{ job.away_team }}</h2>
      {% endif %}
      <p>{{ job.date_time|date:"N j, o" }} at {{ job.date_time|date:"P" }}</p>
      <address>
       {{ job.address_1 }}
       {% if job.address_2 %}{{ job.address_2 }}{% endif %}
       , {{ job.city }}, {{ job.state }} {{ job.zip_code }}
      </address>
     </a>
    </li>
   {% empty %}
    <li>No jobs yet.</li>
   {% endfor %}
  </ul>
 </section>
{% endblock content %}

whistlewatchcards/jobboard/templates/job_add.html
{% extends "base.html" %}
{% load static %}
{% block title %}
 Add Job - Whistle Watch Cards
{% endblock title %}
{% block content %}
 <section>
  <h2>Add Job</h2>
  <form action={% url "job-add" %} method="post">
   {% csrf_token %}
   {{ form }}
   <input type="submit" value="Submit">
  </form>
 </section>
{% endblock content %}

whistlewatchcards/jobboard/templates/job_detail.html
{% extends "base.html" %}
{% load static %}
{% block title %}
 Job {{ job.id }} - Whistle Watch Cards
{% endblock title %}
{% block content %}
 <section>
  Job {{ job.id }}
 </section>
{% endblock content %}